site_name: dena-dive-use-case

nav:
    - Introduction: index.md
    - Installation: installation.md
    - Architecture: architecture.md
    - User guides:
    - API:

theme: material

plugins:
    - mermaid2
    - search
    - autolinks

extra_javascript:
    - https://unpkg.com/mermaid@8.8.4/dist/mermaid.min.js